[tool.black]
line-length = 119
target-version = ['py312']


# isort configuration
[tool.isort]
profile = "black"
line_length = 119
multi_line_output = 3
include_trailing_comma = true
known_standard_library = ["typing"]
known_third_party = [
    "boto3",
    "pandas",
    "botocore",
    "moto",
    "numpy",
    "fastparquet",
    "s3fs",
    "mock",
    "pytz",
    "boto3_type_annotations"
]

# flake8 configuration
[tool.flake8]
max-line-length = 119
exclude = [
    ".git",        # No need to traverse our git directory
    "__pycache__",
]
extend-ignore = []