name: Prod Code Pipeline

on:
  push:
    branches:
      - 'prod'
  pull_request:
    branches:
      - 'prod'

permissions:
  id-token: write
  contents: read

jobs:

  pre-check:
    name: Pre Check
    runs-on: ubuntu-latest
    outputs:
      changed_file_count: ${{ steps.get_changed_file_count.outputs.changed_file_count }}

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Listing changed files for validation
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

  lint-check:
    name: Lint Validation
    runs-on: ubuntu-latest
    needs: pre-check
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
    - name: Code quality checks
      run: |
        pflake8 src

  unit-testing:
    name: Python Unit Testing
    runs-on: ubuntu-latest
    needs: lint-check
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements-ci.txt
            
      - name: Run pytest
        run: |
            pytest tests/unit -v --disable-warnings